default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spaex_development

test:
  <<: *default
  database: spaex_test

production:
  <<: *default
  database: spaex_production
  username: 
  password: 